# restore_images.py
# This script reads a CSV mapping file generated by reorder_and_copy_images.py 
# and restores sequentially named images (e.g., frame_00000.png) back to 
# their original filenames in a new directory.

import csv
import shutil
from pathlib import Path
from argparse import ArgumentParser
import os
from typing import Dict, List

def restore_images_from_csv(sorted_dir: str, mapping_csv_path: str, output_dir: str):
    """
    Reads the filename mapping CSV and restores the images from the sorted directory 
    back to their original names in the output directory.

    Args:
        sorted_dir (str): Path to the directory containing the sorted images (e.g., 'frame_000.png').
        mapping_csv_path (str): Path to the filename_mapping.csv file.
        output_dir (str): Path to the directory where the restored images will be saved.
    """
    
    sorted_path = Path(sorted_dir)
    mapping_csv_file = Path(mapping_csv_path)
    output_path = Path(output_dir)

    # 1. Validate paths
    if not sorted_path.is_dir():
        print(f"Error: Sorted directory not found: {sorted_dir}")
        return
    
    if not mapping_csv_file.is_file():
        print(f"Error: Mapping CSV file not found: {mapping_csv_path}")
        return

    # 2. Create the output directory
    try:
        output_path.mkdir(parents=True, exist_ok=True)
        print(f"Output directory created or already exists: {output_dir}")
    except Exception as e:
        print(f"Error creating output directory: {e}")
        return

    # 3. Read the mapping data from the CSV file
    mapping: List[Dict[str, str]] = []
    try:
        with open(mapping_csv_file, mode='r', newline='') as file:
            reader = csv.DictReader(file)
            for row in reader:
                # Store the necessary mapping (sorted_filename -> original_filename)
                mapping.append({
                    'sorted_filename': row['sorted_filename'],
                    'original_filename': row['original_filename']
                })
        print(f"Successfully loaded {len(mapping)} filename mappings.")
        
    except KeyError:
        print("Error: CSV file missing required columns ('sorted_filename' or 'original_filename').")
        return
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        return

    # 4. Iterate through the mapping and perform the restoration
    restored_count = 0
    print("\nStarting image restoration...")
    
    for item in mapping:
        sorted_name = item['sorted_filename']
        original_name = item['original_filename']
        
        source_file = (sorted_path / sorted_name).with_suffix('.png')
        dest_file = output_path / original_name
        
        if source_file.is_file():
            try:
                # Copy and rename the file
                shutil.copy2(source_file, dest_file)
                # print(f"Restored: {sorted_name} -> {original_name}")
                restored_count += 1
            except Exception as e:
                print(f"Error copying {sorted_name} to {original_name}: {e}")
        else:
            print(f"Warning: Source file not found: {source_file}. Skipping.")
            
    print("\n" + "="*60)
    print(f"✅ Restoration complete! {restored_count} images were restored.")
    print(f"Restored files are saved in: {output_dir}")
    print("="*60)


if __name__ == "__main__":
    parser = ArgumentParser(description="Restore original image names using a CSV mapping.")
    parser.add_argument(
        "--sorted_dir", 
        type=str, 
        default="./data/mip-nerf360/bicycle/sorted_qp=32",
        help="Path to the directory containing the sequential 'frame_xxx.png' images."
    )
    parser.add_argument(
        "--mapping_csv_path", 
        type=str, 
        default="./data/mip-nerf360/bicycle/images_sorted/filename_mapping.csv",
        help="Path to the 'filename_mapping.csv' file generated during sorting."
    )
    parser.add_argument(
        "--output_dir", 
        type=str, 
        default="./data/mip-nerf360/bicycle/images_qp=32", 
        help="Name of the new directory to save the restored images (default: 'restored_images')."
    )

    args = parser.parse_args()
    
    # Example usage:
    # python restore_images.py data/mip-nerf360/bicycle/images_sorted data/mip-nerf360/bicycle/images_sorted/filename_mapping.csv --output_dir data/mip-nerf360/bicycle/images_restored
    
    restore_images_from_csv(
        sorted_dir=args.sorted_dir,
        mapping_csv_path=args.mapping_csv_path,
        output_dir=args.output_dir
    )
